QATlib: 23.11.0 release
Changes from 23.08.0 to 23.11.0:
* Support DC NS (NoSession) APIs
* Support Symmetric Crypto SM3 & SM4
* Support Asymmetric Crypto SM2
* DC compressBound APIs
* Bug Fixes. See Resolved section in README.md

Signed-off-by: Firos Sadarul <firos.sadarul@intel.com>

diff --git a/quickassist/utilities/service/qat_init.sh.in b/quickassist/utilities/service/qat_init.sh.in
--- a/quickassist/utilities/service/qat_init.sh.in
+++ b/quickassist/utilities/service/qat_init.sh.in
@@ -63,10 +63,12 @@ QAT_4XXX_DEVICE_PCI_ID="0x4940"
 QAT_4XXX_DEVICE_PCI_ID_VM="0x4941"
 QAT_401XX_DEVICE_PCI_ID="0x4942"
 QAT_401XX_DEVICE_PCI_ID_VM="0x4943"
+QAT_402XX_DEVICE_PCI_ID="0x4944"
+QAT_402XX_DEVICE_PCI_ID_VM="0x4945"
 QAT_4XXX_DEVICE_NAME="4xxx"
 QAT_4XXX_DRIVER_NAME="qat_4xxx"
 PF_NAMES="$QAT_4XXX_DEVICE_NAME"
-VF_DEVICE_IDS="$QAT_4XXX_DEVICE_PCI_ID_VM $QAT_401XX_DEVICE_PCI_ID_VM"
+VF_DEVICE_IDS="$QAT_4XXX_DEVICE_PCI_ID_VM $QAT_401XX_DEVICE_PCI_ID_VM $QAT_402XX_DEVICE_PCI_ID_VM"
 SERVICES_LIST="sym asym sym;asym dc sym;dc asym;dc dcc"
 SERVICES_ENABLED="NONE"
 SERVICES_ENABLED_FOUND="FALSE"
@@ -130,10 +132,18 @@ sysfs_config() {
     do
         DEV=/sys/bus/pci/devices/$DEV_PCI_ADDR
         PCI_DEV=`cat $DEV/device 2> /dev/null`
-        if [ "$PCI_DEV" != "$QAT_4XXX_DEVICE_PCI_ID" ] && [ "$PCI_DEV" != "$QAT_401XX_DEVICE_PCI_ID" ]; then
+        if [ "$PCI_DEV" != "$QAT_4XXX_DEVICE_PCI_ID" ] && \
+           [ "$PCI_DEV" != "$QAT_401XX_DEVICE_PCI_ID" ] && \
+           [ "$PCI_DEV" != "$QAT_402XX_DEVICE_PCI_ID" ];
+        then
             continue
         fi
 
+        if [ ! -e "$DEV/qat/cfg_services" ]; then
+            echo "Cannot access $DEV/qat/cfg_services: No such file or directory."
+            echo "You may need to update your kernel driver. See QAT kernel release notes."
+            continue
+        fi
         CURRENT_SERVICES=`cat $DEV/qat/cfg_services`
         if [ "$CURRENT_SERVICES" != "$SERVICES_ENABLED" ]; then
             CURRENT_STATE=`cat $DEV/qat/state`
@@ -141,6 +151,11 @@ sysfs_config() {
                 echo down > $DEV/qat/state
             fi
             echo $SERVICES_ENABLED > $DEV/qat/cfg_services
+            if [ $? != 0 ]; then
+                echo "Can't write to cfg_services file: $SERVICES_ENABLED is not supported."
+                echo "You may need to update your kernel driver. See QAT kernel release notes."
+                continue
+            fi
             CURRENT_SERVICES=`cat $DEV/qat/cfg_services`
         fi
         echo "$0, device $DEV_PCI_ADDR configured with services: $CURRENT_SERVICES"
@@ -238,6 +253,10 @@ bind_driver() {
             MODULE=${QAT_4XXX_DRIVER_NAME}vf
              ;;
         $QAT_401XX_DEVICE_PCI_ID_VM )
+            NEW_DRIVER=${QAT_4XXX_DEVICE_NAME}vf
+            MODULE=${QAT_4XXX_DRIVER_NAME}vf
+             ;;
+        $QAT_402XX_DEVICE_PCI_ID_VM )
             NEW_DRIVER=${QAT_4XXX_DEVICE_NAME}vf
             MODULE=${QAT_4XXX_DRIVER_NAME}vf
              ;;
